/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.senzalla.rectify.canvas.panel;

/**
 * @author Bomsalvez
 * @e-mail bomsalvez@gmail.com
 * @github github.com/Bomsalvez
 */
public class PnlMatter extends javax.swing.JPanel {

    /**
     * Creates new form PnlMatterEster
     */
    public PnlMatter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatterProduct = new javax.swing.JLabel();
        cbxMatterProduct = new javax.swing.JComboBox<>();
        lblMatterLiter = new javax.swing.JLabel();
        txtMatterLiter = new javax.swing.JFormattedTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(550, 40));
        setMinimumSize(new java.awt.Dimension(550, 40));
        setPreferredSize(new java.awt.Dimension(550, 40));

        lblMatterProduct.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMatterProduct.setText("Produto");

        cbxMatterProduct.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblMatterLiter.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMatterLiter.setText("Litros");

        txtMatterLiter.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtMatterLiter.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMatterLiter.setPreferredSize(new java.awt.Dimension(120, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMatterProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMatterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lblMatterLiter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatterLiter, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMatterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatterProduct)
                    .addComponent(lblMatterLiter)
                    .addComponent(txtMatterLiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxMatterProduct;
    private javax.swing.JLabel lblMatterLiter;
    private javax.swing.JLabel lblMatterProduct;
    private javax.swing.JFormattedTextField txtMatterLiter;
    // End of variables declaration//GEN-END:variables

}
