package dev.senzalla.rectify.canvas.panel;

import dev.senzalla.rectify.canvas.FrmTrans;
import dev.senzalla.rectify.entitys.LabTank;
import dev.senzalla.rectify.entitys.ReactTrans;
import dev.senzalla.rectify.request.RequestReactTrans;
import dev.senzalla.rectify.treatments.TreatmentLabTank;
import dev.senzalla.theme.TreatmentTheme;

import javax.swing.*;
import java.sql.Time;
import java.util.Date;

/**
 * @author Bomsalvez Freitas
 * @e-mail bomsalvez@gmail.com
 * @github github.com/Bomsalvez
 */
public class PnlReactTrans extends javax.swing.JPanel {

    /**
     * Creates new form PnlReactEster
     *
     * @param trans
     */
    public PnlReactTrans(FrmTrans trans) {
        initComponents();
        TreatmentTheme.initTheme(pnlReact);
        new TreatmentLabTank().showComboBox(cbxLabCar);
    }


    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReact = new javax.swing.JPanel();
        lblEsterReactDt = new javax.swing.JLabel();
        dtcTrans = new com.toedter.calendar.JDateChooser();
        lblEsterReactHrStart = new javax.swing.JLabel();
        txtEsterReactHrStart = new javax.swing.JFormattedTextField();
        txtTransReactMethylate = new javax.swing.JFormattedTextField();
        lblTransReactMethylate = new javax.swing.JLabel();
        cbxLabCar = new javax.swing.JComboBox<>();
        lblEsterReactLabStart = new javax.swing.JLabel();
        lblTransReactPure = new javax.swing.JLabel();
        txtTransReactPure = new javax.swing.JFormattedTextField();
        lblTransReactHrFinal = new javax.swing.JLabel();
        txtTransReactHrFinal = new javax.swing.JFormattedTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(550, 133));
        setMinimumSize(new java.awt.Dimension(550, 133));
        setPreferredSize(new java.awt.Dimension(550, 133));

        lblEsterReactDt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEsterReactDt.setText("Data");

        dtcTrans.setDateFormatString("dd/MM/yyyy");

        lblEsterReactHrStart.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEsterReactHrStart.setText("Hora Inicial");

        try {
            txtEsterReactHrStart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEsterReactHrStart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEsterReactHrStart.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEsterReactHrStart.setPreferredSize(new java.awt.Dimension(120, 27));

        txtTransReactMethylate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtTransReactMethylate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTransReactMethylate.setPreferredSize(new java.awt.Dimension(120, 27));

        lblTransReactMethylate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTransReactMethylate.setText("Metilato");

        cbxLabCar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbxLabCar.setPreferredSize(new java.awt.Dimension(120, 27));

        lblEsterReactLabStart.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEsterReactLabStart.setText("Cod Analise");

        lblTransReactPure.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTransReactPure.setText("Metanol Puro");

        txtTransReactPure.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtTransReactPure.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTransReactPure.setPreferredSize(new java.awt.Dimension(120, 27));

        lblTransReactHrFinal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTransReactHrFinal.setText("Hora Final");

        try {
            txtTransReactHrFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTransReactHrFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTransReactHrFinal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTransReactHrFinal.setPreferredSize(new java.awt.Dimension(120, 27));

        javax.swing.GroupLayout pnlReactLayout = new javax.swing.GroupLayout(pnlReact);
        pnlReact.setLayout(pnlReactLayout);
        pnlReactLayout.setHorizontalGroup(
            pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReactLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEsterReactLabStart)
                    .addComponent(lblEsterReactDt)
                    .addComponent(lblTransReactPure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReactLayout.createSequentialGroup()
                        .addComponent(txtTransReactPure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97)
                        .addComponent(lblTransReactHrFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTransReactHrFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlReactLayout.createSequentialGroup()
                        .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxLabCar, 0, 130, Short.MAX_VALUE)
                            .addComponent(dtcTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96)
                        .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReactLayout.createSequentialGroup()
                                .addComponent(lblEsterReactHrStart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEsterReactHrStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReactLayout.createSequentialGroup()
                                .addComponent(lblTransReactMethylate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTransReactMethylate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlReactLayout.setVerticalGroup(
            pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEsterReactHrStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEsterReactHrStart)
                    .addComponent(lblEsterReactDt)
                    .addComponent(dtcTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEsterReactLabStart)
                    .addComponent(cbxLabCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransReactMethylate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTransReactMethylate))
                .addGap(18, 18, 18)
                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTransReactHrFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTransReactHrFinal)
                        .addComponent(txtTransReactPure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTransReactPure)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cbxLabCar;
    private com.toedter.calendar.JDateChooser dtcTrans;
    private javax.swing.JLabel lblEsterReactDt;
    private javax.swing.JLabel lblEsterReactHrStart;
    private javax.swing.JLabel lblEsterReactLabStart;
    private javax.swing.JLabel lblTransReactHrFinal;
    private javax.swing.JLabel lblTransReactMethylate;
    private javax.swing.JLabel lblTransReactPure;
    private javax.swing.JPanel pnlReact;
    private javax.swing.JFormattedTextField txtEsterReactHrStart;
    private javax.swing.JFormattedTextField txtTransReactHrFinal;
    private javax.swing.JFormattedTextField txtTransReactMethylate;
    private javax.swing.JFormattedTextField txtTransReactPure;
    // End of variables declaration//GEN-END:variables


    public JPanel getPanel() {
        return pnlReact;
    }

    public Date getDate() {
        return dtcTrans.getDate();
    }

    public void save() {
        ReactTrans reactTrans=new ReactTrans();
        reactTrans.setMethylateRctTrans(Integer.parseInt(txtTransReactMethylate.getText()));
        reactTrans.setPureRctTrans(Integer.parseInt(txtTransReactPure.getText()));
        reactTrans.setDtRctTrans(dtcTrans.getDate());
        reactTrans.setHrStartRctTrans(Time.valueOf(txtEsterReactHrStart.getText()));
        reactTrans.setHrFinalRctTrans(Time.valueOf(txtTransReactHrFinal.getText()));
        reactTrans.setLabTank((LabTank) cbxLabCar.getSelectedItem());
        new RequestReactTrans().insert(reactTrans);
    }
}
