package dev.senzalla.rectify.canvas.panel;


/**
 * @author Black Burn Cybernetic
 * @e-mail blackburncyber@gmail.com
 * @github github.com/BlackBurnCybernetic
 */

public class PnlStkTk extends javax.swing.JPanel {

    /** Creates new form pnlStkTk */
    public PnlStkTk() {
        initComponents();
    }
    
    public PnlStkTk(String nameTk, String nameProduct, int literTk){
        initComponents();
        lblLiterTk.setText(Integer.toString(literTk));
        lblNameProduct.setText(nameTk);
        lblNameTk.setText(nameTk);
    }

//    public pnlStkTk(Stk p) {
//        initComponents();
//        lblLiterTk.setText(Integer.toString(p.getQntd()));
//        lblNameProduct.setText(Integer.toString(p.getProle()));
//        lblNameTk.setText(Integer.toString(p.getTank()));
//    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStk = new javax.swing.JPanel();
        iconTk = new javax.swing.JLabel();
        lblNameTk = new javax.swing.JLabel();
        lblLiterTk = new javax.swing.JLabel();
        lblNameProduct = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(148, 140));

        pnlStk.setMaximumSize(new java.awt.Dimension(148, 138));
        pnlStk.setMinimumSize(new java.awt.Dimension(148, 138));
        pnlStk.setPreferredSize(new java.awt.Dimension(148, 138));

        iconTk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconTk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dev/senzalla/rectify/canvas/resource/gas_48dp.png"))); // NOI18N
        iconTk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNameTk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameTk.setText("Tanque");

        lblLiterTk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLiterTk.setText("Litros");

        lblNameProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameProduct.setText("Produto");

        javax.swing.GroupLayout pnlStkLayout = new javax.swing.GroupLayout(pnlStk);
        pnlStk.setLayout(pnlStkLayout);
        pnlStkLayout.setHorizontalGroup(
            pnlStkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLiterTk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNameTk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconTk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .addComponent(lblNameProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlStkLayout.setVerticalGroup(
            pnlStkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStkLayout.createSequentialGroup()
                .addComponent(iconTk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lblNameTk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNameProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLiterTk)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlStk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconTk;
    private javax.swing.JLabel lblLiterTk;
    private javax.swing.JLabel lblNameProduct;
    private javax.swing.JLabel lblNameTk;
    private javax.swing.JPanel pnlStk;
    // End of variables declaration//GEN-END:variables


}
