package dev.senzalla.rectify.frame.panel;

import dev.senzalla.rectify.entitys.ReactionMakeBiodiesel;
import dev.senzalla.rectify.treatments.DateTreatment;
import dev.senzalla.theme.TreatmentTheme;

/**
 * @author Bomsalvez Freitas
 * @e-mail bomsalvez@gmail.com
 * @github github.com/Bomsalvez
 */
public class ReactionBiodieselPanelDetail extends javax.swing.JPanel {

    public ReactionBiodieselPanelDetail(ReactionMakeBiodiesel makeBiodiesel) {
        initComponents();
        initPanel(makeBiodiesel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReact = new javax.swing.JPanel();
        jlabelDate = new javax.swing.JLabel();
        lblDateStart = new javax.swing.JLabel();
        jlabelTimeStart = new javax.swing.JLabel();
        lblTimeStart = new javax.swing.JLabel();
        jlabelMethanol = new javax.swing.JLabel();
        lblMethanol = new javax.swing.JLabel();
        jlabelMethylate = new javax.swing.JLabel();
        lblMethylate = new javax.swing.JLabel();
        jlabelTimeFinal = new javax.swing.JLabel();
        lblTimeFinal = new javax.swing.JLabel();
        jlabelAnlyze = new javax.swing.JLabel();
        jlabelAcidity = new javax.swing.JLabel();
        lblAcidity = new javax.swing.JLabel();
        jlabelSaponity = new javax.swing.JLabel();
        lblSaponity = new javax.swing.JLabel();
        jlabelTrash = new javax.swing.JLabel();
        lblTrash = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(600, 224));
        setMinimumSize(new java.awt.Dimension(600, 224));
        setPreferredSize(new java.awt.Dimension(600, 224));

        pnlReact.setBorder(javax.swing.BorderFactory.createTitledBorder("Reação"));
        pnlReact.setMaximumSize(new java.awt.Dimension(610, 190));
        pnlReact.setMinimumSize(new java.awt.Dimension(610, 190));
        pnlReact.setPreferredSize(new java.awt.Dimension(610, 190));

        jlabelDate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jlabelDate.setText("Data");

        lblDateStart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDateStart.setText("Data");

        jlabelTimeStart.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jlabelTimeStart.setText("Hora Inicial");

        lblTimeStart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTimeStart.setText("Produto");

        jlabelMethanol.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jlabelMethanol.setText("Metanol Puro");

        lblMethanol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMethanol.setText("Produto");

        jlabelMethylate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jlabelMethylate.setText("Metilato");

        lblMethylate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMethylate.setText("Produto");

        jlabelTimeFinal.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jlabelTimeFinal.setText("Hora Final");

        lblTimeFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTimeFinal.setText("Produto");

        jlabelAnlyze.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jlabelAnlyze.setText("Cod Analise");

        jlabelAcidity.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jlabelAcidity.setText("Acidez");

        lblAcidity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAcidity.setText("Produto");

        jlabelSaponity.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jlabelSaponity.setText("Saponidade");

        lblSaponity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSaponity.setText("Produto");

        jlabelTrash.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jlabelTrash.setText("Impureza");

        lblTrash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTrash.setText("Produto");

        javax.swing.GroupLayout pnlReactLayout = new javax.swing.GroupLayout(pnlReact);
        pnlReact.setLayout(pnlReactLayout);
        pnlReactLayout.setHorizontalGroup(
            pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReactLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jlabelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDateStart)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlReactLayout.createSequentialGroup()
                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReactLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlReactLayout.createSequentialGroup()
                                .addComponent(jlabelAnlyze)
                                .addGap(115, 115, 115))
                            .addGroup(pnlReactLayout.createSequentialGroup()
                                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlabelTimeStart)
                                    .addComponent(jlabelMethylate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTimeStart)
                                    .addComponent(lblMethylate))
                                .addGap(73, 73, 73)))
                        .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabelTimeFinal)
                            .addComponent(jlabelMethanol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTimeFinal)
                            .addComponent(lblMethanol)))
                    .addGroup(pnlReactLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jlabelAcidity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAcidity)
                        .addGap(23, 23, 23)
                        .addComponent(jlabelSaponity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaponity)
                        .addGap(18, 18, 18)
                        .addComponent(jlabelTrash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTrash)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlReactLayout.setVerticalGroup(
            pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelDate)
                    .addComponent(lblDateStart))
                .addGap(18, 18, 18)
                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelTimeStart)
                    .addComponent(lblTimeStart)
                    .addComponent(jlabelMethanol)
                    .addComponent(lblMethanol))
                .addGap(18, 18, 18)
                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelMethylate)
                    .addComponent(lblMethylate)
                    .addComponent(jlabelTimeFinal)
                    .addComponent(lblTimeFinal))
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(jlabelAnlyze)
                .addGap(8, 8, 8)
                .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabelTrash)
                        .addComponent(lblTrash))
                    .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabelSaponity)
                        .addComponent(lblSaponity))
                    .addGroup(pnlReactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabelAcidity)
                        .addComponent(lblAcidity)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReact, javax.swing.GroupLayout.PREFERRED_SIZE, 596, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReact, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlabelAcidity;
    private javax.swing.JLabel jlabelAnlyze;
    private javax.swing.JLabel jlabelDate;
    private javax.swing.JLabel jlabelMethanol;
    private javax.swing.JLabel jlabelMethylate;
    private javax.swing.JLabel jlabelSaponity;
    private javax.swing.JLabel jlabelTimeFinal;
    private javax.swing.JLabel jlabelTimeStart;
    private javax.swing.JLabel jlabelTrash;
    private javax.swing.JLabel lblAcidity;
    private javax.swing.JLabel lblDateStart;
    private javax.swing.JLabel lblMethanol;
    private javax.swing.JLabel lblMethylate;
    private javax.swing.JLabel lblSaponity;
    private javax.swing.JLabel lblTimeFinal;
    private javax.swing.JLabel lblTimeStart;
    private javax.swing.JLabel lblTrash;
    private javax.swing.JPanel pnlReact;
    // End of variables declaration//GEN-END:variables

    private void initPanel(ReactionMakeBiodiesel makeBiodiesel) {
        TreatmentTheme.initTheme(pnlReact);
        lblDateStart.setText(DateTreatment.convertDateUtil(makeBiodiesel.getDateReactionMakeBiodiesel()));
        lblTimeStart.setText(String.valueOf(makeBiodiesel.getTimeInitialReactionMakeBiodiesel()));
        lblMethanol.setText(String.valueOf(makeBiodiesel.getMethanolMakeBiodiesel()));
        lblMethylate.setText(String.valueOf(makeBiodiesel.getMethylateMakeBiodiesel()));
        lblTimeFinal.setText(String.valueOf(makeBiodiesel.getTimeFinalReactionMakeBiodiesel()));
        lblAcidity.setText(String.valueOf(makeBiodiesel.getAnalyzeTank().getAcidityAnalyzeTank()));
        lblSaponity.setText(String.valueOf(makeBiodiesel.getAnalyzeTank().getSaponityTank()));
        lblTrash.setText(String.valueOf(makeBiodiesel.getAnalyzeTank().getTrashTank()));
    }
}
