package dev.senzalla.rectify.frame.panel;

import dev.senzalla.theme.TreatmentTheme;

import javax.swing.*;
import java.awt.*;

/**
 * @author Bomsalvez Freitas
 * @e-mail bomsalvez@gmail.com
 * @github github.com/Bomsalvez
 */
public class StockTankPanel extends javax.swing.JPanel {

    public StockTankPanel(String nameTank, String nameProduct, int litterTk) {
        initComponents();
        initPanel(nameTank, nameProduct, litterTk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStockTank = new javax.swing.JPanel();
        iconTank = new javax.swing.JLabel();
        lblTank = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblLiter = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(192, 140));
        setMinimumSize(new java.awt.Dimension(192, 140));
        setPreferredSize(new java.awt.Dimension(192, 140));

        pnlStockTank.setMaximumSize(new java.awt.Dimension(190, 138));
        pnlStockTank.setMinimumSize(new java.awt.Dimension(190, 138));
        pnlStockTank.setPreferredSize(new java.awt.Dimension(190, 138));

        iconTank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconTank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/gas.png"))); // NOI18N
        iconTank.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTank.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTank.setText("Tanque");

        lblProduct.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProduct.setText("Produto");

        lblLiter.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLiter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLiter.setText("Litros");

        javax.swing.GroupLayout pnlStockTankLayout = new javax.swing.GroupLayout(pnlStockTank);
        pnlStockTank.setLayout(pnlStockTankLayout);
        pnlStockTankLayout.setHorizontalGroup(
            pnlStockTankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconTank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        pnlStockTankLayout.setVerticalGroup(
            pnlStockTankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStockTankLayout.createSequentialGroup()
                .addComponent(iconTank, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblTank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLiter)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlStockTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStockTank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconTank;
    private javax.swing.JLabel lblLiter;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblTank;
    private javax.swing.JPanel pnlStockTank;
    // End of variables declaration//GEN-END:variables

    private void initPanel(String nameTank, String nameProduct, int litterTk) {
        TreatmentTheme.initTheme(pnlStockTank);
        this.iconDefine();
        lblLiter.setText(String.valueOf(litterTk));
        lblProduct.setText(nameProduct);
        lblTank.setText(nameTank);
    }

    private void iconDefine() {
        if (pnlStockTank.getBackground().equals(new Color(40, 42, 54))) {
            Icon icon = new ImageIcon(getClass().getResource("/static/img/gas_white.png"));
            iconTank.setIcon(icon);
        }
    }
}
