package dev.senzalla.rectify.frame;

import dev.senzalla.rectify.entitys.Tank;
import dev.senzalla.rectify.treatments.*;
import dev.senzalla.theme.TreatmentTheme;

/**
 * @author Bomsalvez Freitas
 * @e-mail bomsalvez@gmail.com
 * @github github.com/Bomsalvez
 */
public class AnalyzeTankFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmLabTq
     */
    public AnalyzeTankFrame() {
        initComponents();
        initPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLabTk = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTank = new javax.swing.JLabel();
        cbxTank = new javax.swing.JComboBox<>();
        lblAcid = new javax.swing.JLabel();
        txtAcid = new javax.swing.JTextField();
        btnAcid = new javax.swing.JButton();
        lblSoap = new javax.swing.JLabel();
        txtSoap = new javax.swing.JTextField();
        btnSoap = new javax.swing.JButton();
        lblTrash = new javax.swing.JLabel();
        txtTrash = new javax.swing.JFormattedTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1000, 680));
        setMinimumSize(new java.awt.Dimension(1000, 680));
        setNormalBounds(new java.awt.Rectangle(598, 460, 460, 460));
        setPreferredSize(new java.awt.Dimension(1000, 680));

        pnlLabTk.setMaximumSize(new java.awt.Dimension(998, 658));
        pnlLabTk.setMinimumSize(new java.awt.Dimension(998, 658));
        pnlLabTk.setPreferredSize(new java.awt.Dimension(998, 658));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblTitle.setText("Analise Tanque");

        lblTank.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTank.setText("Tanque");

        cbxTank.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        lblAcid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAcid.setText("Acidez");

        txtAcid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAcid.setPreferredSize(new java.awt.Dimension(120, 32));
        txtAcid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAcidKeyTyped(evt);
            }
        });

        btnAcid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/calculadora.png"))); // NOI18N
        btnAcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcidActionPerformed(evt);
            }
        });

        lblSoap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSoap.setText("Saponidade");

        txtSoap.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSoap.setPreferredSize(new java.awt.Dimension(120, 32));
        txtSoap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoapKeyTyped(evt);
            }
        });

        btnSoap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/calculadora.png"))); // NOI18N
        btnSoap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoapActionPerformed(evt);
            }
        });

        lblTrash.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTrash.setText("Impureza");

        txtTrash.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtTrash.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTrash.setPreferredSize(new java.awt.Dimension(120, 32));
        txtTrash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTrashKeyTyped(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSave.setText("Salvar");
        btnSave.setPreferredSize(new java.awt.Dimension(120, 60));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnClear.setText("Limpar");
        btnClear.setPreferredSize(new java.awt.Dimension(120, 60));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setPreferredSize(new java.awt.Dimension(120, 60));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLabTkLayout = new javax.swing.GroupLayout(pnlLabTk);
        pnlLabTk.setLayout(pnlLabTkLayout);
        pnlLabTkLayout.setHorizontalGroup(
            pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabTkLayout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabTkLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLabTkLayout.createSequentialGroup()
                            .addComponent(lblTank)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxTank, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlLabTkLayout.createSequentialGroup()
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(pnlLabTkLayout.createSequentialGroup()
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLabTkLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTrash)
                            .addComponent(lblAcid)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabTkLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSoap)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlLabTkLayout.createSequentialGroup()
                        .addComponent(txtAcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAcid, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(pnlLabTkLayout.createSequentialGroup()
                        .addComponent(txtSoap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSoap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTrash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLabTkLayout.setVerticalGroup(
            pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabTkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(38, 38, 38)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTank))
                .addGap(30, 30, 30)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAcid)
                        .addComponent(txtAcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAcid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSoap)
                    .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoap)))
                .addGap(36, 36, 36)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrash)
                    .addComponent(txtTrash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLabTk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLabTk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtAcidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcidKeyTyped
        NumberField.addNumber(txtAcid.getText(), evt);
    }//GEN-LAST:event_txtAcidKeyTyped

    private void btnAcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcidActionPerformed
        Access.goToInternalFrame(new CalcAcidityFrame(txtAcid));
    }//GEN-LAST:event_btnAcidActionPerformed

    private void txtSoapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoapKeyTyped
        NumberField.addNumber(txtSoap.getText(), evt);
    }//GEN-LAST:event_txtSoapKeyTyped

    private void btnSoapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoapActionPerformed
        Access.goToInternalFrame(new CalcSaponityFrame(txtSoap));
    }//GEN-LAST:event_btnSoapActionPerformed

    private void txtTrashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTrashKeyTyped
        NumberField.txtNumberInt(evt);
    }//GEN-LAST:event_txtTrashKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (TxtTreatment.isTextFieldEmpty(pnlLabTk) && ComboBoxTreatment.isCbxEmpty(pnlLabTk)) {
            new AnalyzeTankTreatment().saveLabTank((Tank) cbxTank.getSelectedItem(), txtAcid.getText(), txtSoap.getText(), txtTrash.getText());
            TxtTreatment.cleanTextField(pnlLabTk);
            ComboBoxTreatment.cleanCbx(pnlLabTk);
        } else {
            PopUp.fieldIsEmpty();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        TxtTreatment.cleanTextField(pnlLabTk);
        ComboBoxTreatment.cleanCbx(pnlLabTk);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcid;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSoap;
    private javax.swing.JComboBox<Object> cbxTank;
    private javax.swing.JLabel lblAcid;
    private javax.swing.JLabel lblSoap;
    private javax.swing.JLabel lblTank;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrash;
    private javax.swing.JPanel pnlLabTk;
    private javax.swing.JTextField txtAcid;
    private javax.swing.JTextField txtSoap;
    private javax.swing.JFormattedTextField txtTrash;
    // End of variables declaration//GEN-END:variables

    private void initPanel() {
        TreatmentTheme.initTheme(pnlLabTk);
        TankTreatment.initComboBox(cbxTank);
        TreatmentTheme.iconDefine(btnAcid, "static/img/calculadora_white.png");
        TreatmentTheme.iconDefine(btnSoap, "static/img/calculadora_white.png");
    }

}
