package dev.senzalla.rectify.frame;

import dev.senzalla.rectify.calc.CalcTransport;
import dev.senzalla.rectify.entitys.*;
import dev.senzalla.rectify.request.DriverRequest;
import dev.senzalla.rectify.treatments.*;
import dev.senzalla.theme.TreatmentTheme;

/**
 * @author Bomsalvez Freitas
 * @e-mail bomsalvez@gmail.com
 * @github github.com/Bomsalvez
 */
public class DeschargeFrame extends javax.swing.JInternalFrame {

    private boolean driverEmpty = true;
    private Driver driver;

    /**
     * Creates new form FrmDcharge
     */
    public DeschargeFrame() {
        initComponents();
        initPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCharge = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblProvider = new javax.swing.JLabel();
        cbxProvider = new javax.swing.JComboBox<>();
        lblDtOf = new javax.swing.JLabel();
        dtcDtOf = new com.toedter.calendar.JDateChooser();
        lblHrOf = new javax.swing.JLabel();
        txtHrOf = new javax.swing.JFormattedTextField();
        lblNote = new javax.swing.JLabel();
        spnNote = new javax.swing.JSpinner();
        lblTicket = new javax.swing.JLabel();
        spnTicket = new javax.swing.JSpinner();
        lblBoard = new javax.swing.JLabel();
        txtBoard = new javax.swing.JTextField();
        lblCnh = new javax.swing.JLabel();
        txtCnh = new javax.swing.JFormattedTextField();
        lblDriver = new javax.swing.JLabel();
        txtDriver = new javax.swing.JTextField();
        lblDtUp = new javax.swing.JLabel();
        dtcDtUp = new com.toedter.calendar.JDateChooser();
        lblHrUp = new javax.swing.JLabel();
        txtHrUp = new javax.swing.JFormattedTextField();
        lblProduct = new javax.swing.JLabel();
        cbxProduct = new javax.swing.JComboBox<>();
        lblanalyzeTruck = new javax.swing.JLabel();
        cbxAnalyzeTruck = new javax.swing.JComboBox<>();
        lblBurden = new javax.swing.JLabel();
        txtBurden = new javax.swing.JFormattedTextField();
        lblLitter = new javax.swing.JLabel();
        txtLitter = new javax.swing.JTextField();
        lblTank = new javax.swing.JLabel();
        cbxTank = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1000, 680));
        setMinimumSize(new java.awt.Dimension(1000, 680));
        setPreferredSize(new java.awt.Dimension(1000, 680));

        pnlCharge.setMaximumSize(new java.awt.Dimension(750, 765));
        pnlCharge.setMinimumSize(new java.awt.Dimension(750, 765));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblTitle.setText("Descarregamento");

        lblProvider.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblProvider.setText("Fornecedor");

        cbxProvider.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        lblDtOf.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDtOf.setText("Data Entrada");

        dtcDtOf.setDateFormatString("dd/MM/yyyy");
        dtcDtOf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblHrOf.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblHrOf.setText("Hora Entrada");

        try {
            txtHrOf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHrOf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHrOf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtHrOf.setPreferredSize(new java.awt.Dimension(120, 27));

        lblNote.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNote.setText("Nota N°");

        spnNote.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        spnNote.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spnNote.setPreferredSize(new java.awt.Dimension(70, 32));

        lblTicket.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTicket.setText("Ticket");

        spnTicket.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        spnTicket.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spnTicket.setPreferredSize(new java.awt.Dimension(70, 32));

        lblBoard.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBoard.setText("Placa");

        txtBoard.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBoard.setPreferredSize(new java.awt.Dimension(120, 27));
        txtBoard.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBoardFocusLost(evt);
            }
        });

        lblCnh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCnh.setText("CNH");

        txtCnh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCnh.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCnh.setPreferredSize(new java.awt.Dimension(120, 27));
        txtCnh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCnhFocusLost(evt);
            }
        });
        txtCnh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCnhKeyTyped(evt);
            }
        });

        lblDriver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDriver.setText("Motorista");

        txtDriver.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDriver.setPreferredSize(new java.awt.Dimension(120, 27));

        lblDtUp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDtUp.setText("Data Saida");

        dtcDtUp.setDateFormatString("dd/MM/yyyy");
        dtcDtUp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblHrUp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblHrUp.setText("Hora Saida");

        try {
            txtHrUp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHrUp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHrUp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtHrUp.setPreferredSize(new java.awt.Dimension(120, 27));

        lblProduct.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblProduct.setText("Produto");

        cbxProduct.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        lblanalyzeTruck.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblanalyzeTruck.setText("Analise");

        cbxAnalyzeTruck.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        lblBurden.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBurden.setText("Peso");

        txtBurden.setEditable(false);
        txtBurden.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtBurden.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBurden.setPreferredSize(new java.awt.Dimension(120, 27));
        txtBurden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBurdenKeyTyped(evt);
            }
        });

        lblLitter.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLitter.setText("Litros");

        txtLitter.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtLitter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLitterFocusLost(evt);
            }
        });

        lblTank.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTank.setText("Tanque");

        cbxTank.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        btnSave.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSave.setText("Salvar");
        btnSave.setPreferredSize(new java.awt.Dimension(120, 60));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnClear.setText("Limpar");
        btnClear.setPreferredSize(new java.awt.Dimension(120, 60));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setPreferredSize(new java.awt.Dimension(120, 60));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChargeLayout = new javax.swing.GroupLayout(pnlCharge);
        pnlCharge.setLayout(pnlChargeLayout);
        pnlChargeLayout.setHorizontalGroup(
                pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblDtOf)
                                                        .addComponent(lblProvider)
                                                        .addComponent(lblNote)
                                                        .addComponent(lblBoard)
                                                        .addComponent(lblDriver)
                                                        .addComponent(lblDtUp)
                                                        .addComponent(lblProduct)
                                                        .addComponent(lblanalyzeTruck)
                                                        .addComponent(lblTank)
                                                        .addComponent(lblLitter))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlChargeLayout.createSequentialGroup()
                                                                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addComponent(spnNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(txtBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(lblCnh, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(lblTicket, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                                                                .addComponent(dtcDtUp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(lblHrUp))
                                                                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                                                                .addComponent(dtcDtOf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                                                                .addComponent(lblHrOf))
                                                                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                                                                .addComponent(txtLitter, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(lblBurden)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtCnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(txtHrUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(txtHrOf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(spnTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChargeLayout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(txtBurden, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addComponent(txtDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbxProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbxProvider, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbxTank, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cbxAnalyzeTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                                .addGap(260, 260, 260)
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(60, 60, 60)
                                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(61, 61, 61)
                                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                                .addGap(368, 368, 368)
                                                .addComponent(lblTitle)))
                                .addContainerGap())
        );
        pnlChargeLayout.setVerticalGroup(
                pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle)
                                .addGap(30, 30, 30)
                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblHrOf)
                                                .addComponent(txtHrOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblProvider)
                                                        .addComponent(cbxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblDtOf)
                                                        .addComponent(dtcDtOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblNote)
                                        .addComponent(lblTicket)
                                        .addComponent(spnNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblBoard)
                                        .addComponent(txtBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCnh)
                                        .addComponent(txtCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlChargeLayout.createSequentialGroup()
                                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblDriver)
                                                        .addComponent(txtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblDtUp)
                                                        .addComponent(dtcDtUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblHrUp)
                                                .addComponent(txtHrUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblProduct)
                                        .addComponent(cbxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblanalyzeTruck)
                                        .addComponent(cbxAnalyzeTruck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblBurden)
                                        .addComponent(txtBurden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblLitter)
                                        .addComponent(txtLitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTank)
                                        .addComponent(cbxTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlChargeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
        );

        jScrollPane1.setViewportView(pnlCharge);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBoardFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBoardFocusLost
        txtBoard.setText(txtBoard.getText().toUpperCase());
    }//GEN-LAST:event_txtBoardFocusLost

    private void txtCnhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnhKeyTyped
        NumberField.txtNumberInt(evt);
    }//GEN-LAST:event_txtCnhKeyTyped

    private void txtCnhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCnhFocusLost
        driver = new DriverRequest().selectCnh(txtCnh.getText());
        if (driver != null) {
            driverEmpty = false;
            txtDriver.setText(driver.getNameDriver());
        }
    }//GEN-LAST:event_txtCnhFocusLost

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (TxtTreatment.isTextFieldEmpty(pnlCharge) && ComboBoxTreatment.isCbxEmpty(pnlCharge) && SpinnerTreatment.isSpinnerVoid(pnlCharge) && DateChooserTreatment.isDateChooserNull(pnlCharge)) {
            if (driverEmpty) {
                new DriverTreatment().saveDriver(txtDriver.getText(), txtCnh.getText());
                driver = new DriverRequest().selectCnh(txtCnh.getText());
            }
            new DischargeTreatment().saveDchage((Provider) cbxProvider.getSelectedItem(), dtcDtOf.getDate(), txtHrOf.getText(), (Integer) spnNote.getValue(), (Integer) spnTicket.getValue(), txtBoard.getText(), driver, dtcDtUp.getDate(), txtHrUp.getText(), (Product) cbxProduct.getSelectedItem(), (AnalyzeTruck) cbxAnalyzeTruck.getSelectedItem(), txtBurden.getText(), txtLitter.getText(), (Tank) cbxTank.getSelectedItem());
            Access.goToInternalFrame(this, new DeschargeFrame());
        } else {
            PopUp.fieldIsEmpty();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Access.goToInternalFrame(this, new DeschargeFrame());
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtBurdenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBurdenKeyTyped
        NumberField.txtNumberInt(evt);
    }//GEN-LAST:event_txtBurdenKeyTyped

    private void txtLitterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLitterFocusLost
        if (cbxAnalyzeTruck.getSelectedIndex() > 0 && !txtLitter.getText().equals("")) {
            int litter = CalcTransport.calcBurden((AnalyzeTruck) cbxAnalyzeTruck.getSelectedItem(), Integer.parseInt((txtLitter.getText())));
            txtBurden.setText(String.valueOf(litter));
        }
    }//GEN-LAST:event_txtLitterFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> cbxAnalyzeTruck;
    private javax.swing.JComboBox<Object> cbxProduct;
    private javax.swing.JComboBox<Object> cbxProvider;
    private javax.swing.JComboBox<Object> cbxTank;
    private com.toedter.calendar.JDateChooser dtcDtOf;
    private com.toedter.calendar.JDateChooser dtcDtUp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBoard;
    private javax.swing.JLabel lblBurden;
    private javax.swing.JLabel lblCnh;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblDtOf;
    private javax.swing.JLabel lblDtUp;
    private javax.swing.JLabel lblHrOf;
    private javax.swing.JLabel lblHrUp;
    private javax.swing.JLabel lblLitter;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProvider;
    private javax.swing.JLabel lblTank;
    private javax.swing.JLabel lblTicket;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblanalyzeTruck;
    private javax.swing.JPanel pnlCharge;
    private javax.swing.JSpinner spnNote;
    private javax.swing.JSpinner spnTicket;
    private javax.swing.JTextField txtBoard;
    private javax.swing.JFormattedTextField txtBurden;
    private javax.swing.JFormattedTextField txtCnh;
    private javax.swing.JTextField txtDriver;
    private javax.swing.JFormattedTextField txtHrOf;
    private javax.swing.JFormattedTextField txtHrUp;
    private javax.swing.JTextField txtLitter;
    // End of variables declaration//GEN-END:variables

    private void initPanel() {
        TreatmentTheme.initTheme(pnlCharge);
        ProductTreatment.initComboBox(cbxProduct);
        ProviderTreatment.initComboBox(cbxProvider);
        TankTreatment.initComboBox(cbxTank);
        AnalyzeTruckTreatment.initComboBoxAnalyze(cbxAnalyzeTruck);
    }

}
