package dev.senzalla.rectify.frame;

import dev.senzalla.rectify.entitys.MakeEster;
import dev.senzalla.rectify.entitys.Tank;
import dev.senzalla.rectify.frame.panel.MatterPanel;
import dev.senzalla.rectify.frame.panel.ReactionEsterPanel;
import dev.senzalla.rectify.treatments.*;
import dev.senzalla.theme.TreatmentTheme;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Bomsalvez Freitas
 * @e-mail bomsalvez@gmail.com
 * @github github.com/Bomsalvez
 */
public class MakeEsterFrame extends javax.swing.JInternalFrame {

    private int countMatter;
    private int countReact;
    private BoxLayout layoutMatter;
    private BoxLayout layoutReact;
    private List<MatterPanel> pnlMatter;
    private List<ReactionEsterPanel> pnlReact;

    /**
     * Creates new form FrmLabTqTbl
     */
    public MakeEsterFrame() {
        this.initComponents();
        initPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roll = new javax.swing.JScrollPane();
        pnlEster = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTank = new javax.swing.JLabel();
        cbxTank = new javax.swing.JComboBox<>();
        pnlMatterEster = new javax.swing.JPanel();
        btnMatterEsterAdd = new javax.swing.JButton();
        btnMatterEsterRmv = new javax.swing.JButton();
        lblEsterAmount = new javax.swing.JLabel();
        txtEsterAmount = new javax.swing.JFormattedTextField();
        pnlReactEster = new javax.swing.JPanel();
        btnReactEsterAdd = new javax.swing.JButton();
        btnReactEsterRmv = new javax.swing.JButton();
        lblEsterTrash = new javax.swing.JLabel();
        txtEsterTrash = new javax.swing.JFormattedTextField();
        lblEsterProduced = new javax.swing.JLabel();
        txtEsterProduced = new javax.swing.JFormattedTextField();
        btnEsterSave = new javax.swing.JButton();
        btnEsterClear = new javax.swing.JButton();
        btnEsterCancel = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1000, 680));
        setMinimumSize(new java.awt.Dimension(1000, 680));
        setPreferredSize(new java.awt.Dimension(1000, 680));

        roll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        roll.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                rollMouseWheelMoved(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblTitle.setText("Esterificação");

        lblTank.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTank.setText("Tanque");

        cbxTank.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        pnlMatterEster.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlMatterEster.setLayout(new javax.swing.BoxLayout(pnlMatterEster, javax.swing.BoxLayout.Y_AXIS));

        btnMatterEsterAdd.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnMatterEsterAdd.setText("Adicionar Produto");
        btnMatterEsterAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatterEsterAddActionPerformed(evt);
            }
        });

        btnMatterEsterRmv.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnMatterEsterRmv.setText("Eliminar Produto");
        btnMatterEsterRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatterEsterRmvActionPerformed(evt);
            }
        });

        lblEsterAmount.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblEsterAmount.setText("Quantidade Total");

        txtEsterAmount.setEditable(false);
        txtEsterAmount.setBackground(new java.awt.Color(69, 73, 74));
        txtEsterAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtEsterAmount.setFocusable(false);
        txtEsterAmount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtEsterAmount.setPreferredSize(new java.awt.Dimension(120, 32));

        pnlReactEster.setLayout(new javax.swing.BoxLayout(pnlReactEster, javax.swing.BoxLayout.LINE_AXIS));

        btnReactEsterAdd.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnReactEsterAdd.setText("Adicionar Reação");
        btnReactEsterAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactEsterAddActionPerformed(evt);
            }
        });

        btnReactEsterRmv.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnReactEsterRmv.setText("Eliminar Reação");
        btnReactEsterRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactEsterRmvActionPerformed(evt);
            }
        });

        lblEsterTrash.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblEsterTrash.setText("Residuo");

        txtEsterTrash.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtEsterTrash.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtEsterTrash.setPreferredSize(new java.awt.Dimension(100, 32));

        lblEsterProduced.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblEsterProduced.setText("Total Produzido");

        txtEsterProduced.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtEsterProduced.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtEsterProduced.setPreferredSize(new java.awt.Dimension(100, 32));

        btnEsterSave.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnEsterSave.setText("Salvar");
        btnEsterSave.setPreferredSize(new java.awt.Dimension(120, 60));
        btnEsterSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsterSaveActionPerformed(evt);
            }
        });

        btnEsterClear.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnEsterClear.setText("Limpar");
        btnEsterClear.setPreferredSize(new java.awt.Dimension(120, 60));
        btnEsterClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsterClearActionPerformed(evt);
            }
        });

        btnEsterCancel.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnEsterCancel.setText("Cancelar");
        btnEsterCancel.setPreferredSize(new java.awt.Dimension(120, 60));
        btnEsterCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsterCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEsterLayout = new javax.swing.GroupLayout(pnlEster);
        pnlEster.setLayout(pnlEsterLayout);
        pnlEsterLayout.setHorizontalGroup(
            pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEsterLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEsterLayout.createSequentialGroup()
                                .addComponent(lblEsterAmount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEsterAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEsterLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lblEsterTrash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEsterTrash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(lblEsterProduced)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEsterProduced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlEsterLayout.createSequentialGroup()
                            .addComponent(btnEsterSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62)
                            .addComponent(btnEsterClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62)
                            .addComponent(btnEsterCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlEsterLayout.createSequentialGroup()
                        .addComponent(btnReactEsterAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(btnReactEsterRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEsterLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblTank)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTank, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEsterLayout.createSequentialGroup()
                        .addComponent(btnMatterEsterAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMatterEsterRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(309, 309, 309))
            .addGroup(pnlEsterLayout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEsterLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlReactEster, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addComponent(pnlMatterEster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(239, 239, 239))
        );
        pnlEsterLayout.setVerticalGroup(
            pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEsterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addGroup(pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTank)
                    .addComponent(cbxTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(pnlMatterEster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMatterEsterAdd)
                    .addComponent(btnMatterEsterRmv))
                .addGap(24, 24, 24)
                .addGroup(pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEsterAmount)
                    .addComponent(txtEsterAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(pnlReactEster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReactEsterAdd)
                    .addComponent(btnReactEsterRmv))
                .addGap(27, 27, 27)
                .addGroup(pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEsterTrash)
                    .addComponent(txtEsterTrash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEsterProduced)
                    .addComponent(txtEsterProduced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEsterClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEsterCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEsterSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        roll.setViewportView(pnlEster);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatterEsterAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatterEsterAddActionPerformed
        if (countMatter <= 1) {
            defineButton(btnMatterEsterRmv, true);
        } else if (countMatter >= 6) {
            defineButton(btnMatterEsterAdd, false);
        }
        addPanelMatter();
    }//GEN-LAST:event_btnMatterEsterAddActionPerformed

    private void btnMatterEsterRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatterEsterRmvActionPerformed
        pnlMatter.get(--countMatter).minusLitters();
        if (countMatter <= 1) {
            defineButton(btnMatterEsterRmv, false);
        } else if (countMatter <= 6) {
            defineButton(btnMatterEsterAdd, true);
        }
        pnlMatter.get(countMatter).setVisible(false);
        pnlMatter.remove(countMatter);
    }//GEN-LAST:event_btnMatterEsterRmvActionPerformed

    private void btnReactEsterAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactEsterAddActionPerformed
        if (countReact <= 1) {
            defineButton(btnReactEsterRmv, true);
        } else if (countReact >= 6) {
            defineButton(btnReactEsterAdd, false);
        }
        addPanelReact();
    }//GEN-LAST:event_btnReactEsterAddActionPerformed

    private void btnReactEsterRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactEsterRmvActionPerformed
        countReact--;
        if (countReact <= 1) {
            defineButton(btnReactEsterRmv, false);
        } else if (countReact <= 6) {
            defineButton(btnReactEsterAdd, true);
        }
        this.pnlReact.get(countReact).setVisible(false);
        this.pnlReact.remove(countReact);
    }//GEN-LAST:event_btnReactEsterRmvActionPerformed

    private void btnEsterSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsterSaveActionPerformed
        boolean react = ReactionEsterTreatment.checkReact(pnlReact);
        boolean matter = checkMatter();
        if (matter && react && TxtTreatment.isTextFieldEmpty(pnlEster)) {
            new MakeEsterTreatment().saveMakeEster((Tank) cbxTank.getSelectedItem(), txtEsterAmount.getText(), txtEsterProduced.getText(), txtEsterTrash.getText(), pnlReact.get(0).getDate());
            pnlMatter.forEach(MatterPanel::saveEster);
            pnlReact.forEach(ReactionEsterPanel::save);
            Access.goToInternalFrame(this, new MakeEsterFrame());
        } else {
            PopUp.fieldIsEmpty();
        }
    }//GEN-LAST:event_btnEsterSaveActionPerformed


    private void btnEsterClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsterClearActionPerformed
        Access.goToInternalFrame(this, new MakeEsterFrame());
    }//GEN-LAST:event_btnEsterClearActionPerformed

    private void btnEsterCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsterCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnEsterCancelActionPerformed

    private void rollMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_rollMouseWheelMoved
        ItemTreatment.speedRoll(roll);
    }//GEN-LAST:event_rollMouseWheelMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsterCancel;
    private javax.swing.JButton btnEsterClear;
    private javax.swing.JButton btnEsterSave;
    private javax.swing.JButton btnMatterEsterAdd;
    private javax.swing.JButton btnMatterEsterRmv;
    private javax.swing.JButton btnReactEsterAdd;
    private javax.swing.JButton btnReactEsterRmv;
    private javax.swing.JComboBox<Object> cbxTank;
    private javax.swing.JLabel lblEsterAmount;
    private javax.swing.JLabel lblEsterProduced;
    private javax.swing.JLabel lblEsterTrash;
    private javax.swing.JLabel lblTank;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlEster;
    private javax.swing.JPanel pnlMatterEster;
    private javax.swing.JPanel pnlReactEster;
    private javax.swing.JScrollPane roll;
    private javax.swing.JFormattedTextField txtEsterAmount;
    private javax.swing.JFormattedTextField txtEsterProduced;
    private javax.swing.JFormattedTextField txtEsterTrash;
    // End of variables declaration//GEN-END:variables

    private void initPanelMatter() {
        this.layoutMatter = new BoxLayout(pnlMatterEster, 1);
        this.pnlMatter = new ArrayList<>();
        addPanelMatter();

    }

    private void addPanelMatter() {
        MatterPanel panel = new MatterPanel(txtEsterAmount, countMatter++);
        this.pnlMatterEster.setLayout(layoutMatter);
        this.pnlMatter.add(panel);
        this.pnlMatterEster.add(panel).setVisible(true);
    }

    private void initPanelReact() {
        this.layoutReact = new BoxLayout(pnlReactEster, 1);
        this.pnlReact = new ArrayList<>();
        addPanelReact();
    }

    private void addPanelReact() {
        ReactionEsterPanel panel = new ReactionEsterPanel(this);
        this.pnlReactEster.setLayout(layoutReact);
        this.pnlReact.add(panel);
        this.pnlReactEster.add(panel).setVisible(true);
        this.countReact++;
    }

    private void defineButton(JButton btn, boolean b) {
        btn.setEnabled(b);
        btn.setVisible(b);
    }

    public Tank getTank() {
        if (cbxTank.getSelectedIndex() > 0) {
            return (Tank) cbxTank.getSelectedItem();
        }
        return null;
    }

    private boolean checkMatter() {
        return pnlMatter.stream().anyMatch(pnl -> TxtTreatment.isTextFieldEmpty(pnl.getPanel()) || ComboBoxTreatment.isCbxEmpty(pnl.getPanel()));
    }

    private void initPanel() {
        this.initPanelMatter();
        this.initPanelReact();
        this.defineButton(btnMatterEsterRmv, false);
        this.defineButton(btnReactEsterRmv, false);
        TreatmentTheme.initTheme(pnlEster);
        TankTreatment.initComboBox(cbxTank);
        PnlMatterTreatment.initEster();
    }
}
