package dev.senzalla.rectify.frame;

import dev.senzalla.rectify.entitys.Provider;
import dev.senzalla.rectify.treatments.*;
import dev.senzalla.theme.TreatmentTheme;

/**
 * @author Bomsalvez Freitas
 * @e-mail bomsalvez@gmail.com
 * @github github.com/Bomsalvez
 */
public class SampleFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmLabTqTbl
     */
    public SampleFrame() {
        initComponents();
        TreatmentTheme.initTheme(pnlSeal);
        ProviderTreatment.initComboBox(cbxProvider);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSeal = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblProvider = new javax.swing.JLabel();
        cbxProvider = new javax.swing.JComboBox<>();
        lblSale = new javax.swing.JLabel();
        txtSale = new javax.swing.JFormattedTextField();
        lblSeal = new javax.swing.JLabel();
        lblClient = new javax.swing.JLabel();
        txtClient = new javax.swing.JFormattedTextField();
        lblFactory = new javax.swing.JLabel();
        txtFactory = new javax.swing.JFormattedTextField();
        lblBr = new javax.swing.JLabel();
        txtBr = new javax.swing.JFormattedTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1000, 680));
        setMinimumSize(new java.awt.Dimension(1000, 680));
        setPreferredSize(new java.awt.Dimension(1000, 680));

        pnlSeal.setMaximumSize(new java.awt.Dimension(998, 658));
        pnlSeal.setMinimumSize(new java.awt.Dimension(998, 658));
        pnlSeal.setPreferredSize(new java.awt.Dimension(998, 658));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("Etiqueta BioDiesel");

        lblProvider.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblProvider.setText("Cliente");

        cbxProvider.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        lblSale.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSale.setText("Leilão");

        txtSale.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtSale.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSale.setPreferredSize(new java.awt.Dimension(100, 27));
        txtSale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaleKeyTyped(evt);
            }
        });

        lblSeal.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblSeal.setForeground(new java.awt.Color(255, 0, 0));
        lblSeal.setText("Lacres");

        lblClient.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblClient.setText("Cliente");

        txtClient.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtClient.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtClient.setPreferredSize(new java.awt.Dimension(100, 27));
        txtClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClientKeyTyped(evt);
            }
        });

        lblFactory.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFactory.setText("Fabrica");

        txtFactory.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtFactory.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtFactory.setPreferredSize(new java.awt.Dimension(100, 27));
        txtFactory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFactoryKeyTyped(evt);
            }
        });

        lblBr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBr.setText("Petrobras");

        txtBr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtBr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBr.setPreferredSize(new java.awt.Dimension(100, 27));
        txtBr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBrKeyTyped(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSave.setText("Salvar");
        btnSave.setPreferredSize(new java.awt.Dimension(120, 60));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnClear.setText("Limpar");
        btnClear.setPreferredSize(new java.awt.Dimension(120, 60));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setPreferredSize(new java.awt.Dimension(120, 60));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSealLayout = new javax.swing.GroupLayout(pnlSeal);
        pnlSeal.setLayout(pnlSealLayout);
        pnlSealLayout.setHorizontalGroup(
            pnlSealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSealLayout.createSequentialGroup()
                .addGroup(pnlSealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSealLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(pnlSealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProvider)
                            .addComponent(lblSale)
                            .addComponent(lblSeal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSealLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSealLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(lblClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClient, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(lblFactory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFactory, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lblBr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBr, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSealLayout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(lblTitle)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        pnlSealLayout.setVerticalGroup(
            pnlSealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSealLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(51, 51, 51)
                .addGroup(pnlSealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProvider)
                    .addComponent(cbxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlSealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSale)
                    .addComponent(txtSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(lblSeal)
                .addGap(35, 35, 35)
                .addGroup(pnlSealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClient)
                    .addComponent(txtClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFactory)
                    .addComponent(txtFactory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBr)
                    .addComponent(txtBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(pnlSealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaleKeyTyped
        NumberField.txtNumberInt(evt);
    }//GEN-LAST:event_txtSaleKeyTyped

    private void txtClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientKeyTyped
        NumberField.txtNumberInt(evt);
    }//GEN-LAST:event_txtClientKeyTyped

    private void txtFactoryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFactoryKeyTyped
        NumberField.txtNumberInt(evt);
    }//GEN-LAST:event_txtFactoryKeyTyped

    private void txtBrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrKeyTyped
        NumberField.txtNumberInt(evt);
    }//GEN-LAST:event_txtBrKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (TxtTreatment.isTextFieldEmpty(pnlSeal) && cbxProvider.getSelectedIndex() > 0) {
            new SampleTreatment().saveSample(txtSale.getText(), txtFactory.getText(), txtClient.getText(), txtBr.getText(), (Provider) cbxProvider.getSelectedItem());
            TxtTreatment.cleanTextField(pnlSeal);
            ComboBoxTreatment.cleanCbx(pnlSeal);
        } else {
            PopUp.fieldIsEmpty();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        TxtTreatment.cleanTextField(pnlSeal);
        ComboBoxTreatment.cleanCbx(pnlSeal);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> cbxProvider;
    private javax.swing.JLabel lblBr;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblFactory;
    private javax.swing.JLabel lblProvider;
    private javax.swing.JLabel lblSale;
    private javax.swing.JLabel lblSeal;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlSeal;
    private javax.swing.JFormattedTextField txtBr;
    private javax.swing.JFormattedTextField txtClient;
    private javax.swing.JFormattedTextField txtFactory;
    private javax.swing.JFormattedTextField txtSale;
    // End of variables declaration//GEN-END:variables

}
