/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.senzalla.rectify.canvas;

import dev.senzalla.rectify.calc.CalcSoap;
import dev.senzalla.rectify.canvas.panel.PnlCalcOleic;
import dev.senzalla.rectify.exception.EmptyField;
import dev.senzalla.rectify.request.HclRequest;
import dev.senzalla.rectify.treatments.NumberField;
import dev.senzalla.rectify.treatments.TxtTreatment;

import java.awt.GridLayout;

/**
 * @author Black Burn Cybernetic
 * @e-mail blackburncyber@gmail.com
 * @github github.com/BlackBurnCybernetic
 */
public class FrmCalcSoap extends javax.swing.JInternalFrame {
    String soap;

    /**
     * Creates new form FrmCalcSoap
     */
    public FrmCalcSoap() {
        initComponents();
        showComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCalcSoap = new javax.swing.JPanel();
        btnMain = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblConcentration = new javax.swing.JLabel();
        cbxConcentration = new javax.swing.JComboBox<>();
        lblMass = new javax.swing.JLabel();
        txtMass = new javax.swing.JTextField();
        lblBulk = new javax.swing.JLabel();
        txtBulk = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        pnlCalc = new javax.swing.JPanel();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(598, 460));
        setMinimumSize(new java.awt.Dimension(598, 460));
        setPreferredSize(new java.awt.Dimension(598, 460));

        pnlCalcSoap.setMaximumSize(new java.awt.Dimension(596, 438));
        pnlCalcSoap.setMinimumSize(new java.awt.Dimension(596, 438));
        pnlCalcSoap.setPreferredSize(new java.awt.Dimension(596, 438));

        btnMain.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMain.setText("<<");
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblTitle.setText("Calculadora Saponidade");

        lblConcentration.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConcentration.setText("Concentração");

        cbxConcentration.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblMass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMass.setText("Massa");

        txtMass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMassKeyTyped(evt);
            }
        });

        lblBulk.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBulk.setText("Volume");

        txtBulk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBulkKeyTyped(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        btnCalculate.setText("Calcular");
        btnCalculate.setPreferredSize(new java.awt.Dimension(500, 90));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCalcLayout = new javax.swing.GroupLayout(pnlCalc);
        pnlCalc.setLayout(pnlCalcLayout);
        pnlCalcLayout.setHorizontalGroup(
                pnlCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCalcLayout.setVerticalGroup(
                pnlCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 152, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlCalcSoapLayout = new javax.swing.GroupLayout(pnlCalcSoap);
        pnlCalcSoap.setLayout(pnlCalcSoapLayout);
        pnlCalcSoapLayout.setHorizontalGroup(
                pnlCalcSoapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCalcSoapLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlCalcSoapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlCalcSoapLayout.createSequentialGroup()
                                                .addComponent(btnMain)
                                                .addGap(121, 121, 121)
                                                .addComponent(lblTitle)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCalcSoapLayout.createSequentialGroup()
                                                .addGap(0, 21, Short.MAX_VALUE)
                                                .addGroup(pnlCalcSoapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCalcSoapLayout.createSequentialGroup()
                                                                .addComponent(lblConcentration)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cbxConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(73, 73, 73)
                                                                .addComponent(lblMass)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtMass, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(65, 65, 65)
                                                                .addComponent(lblBulk)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtBulk, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(24, 24, 24))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCalcSoapLayout.createSequentialGroup()
                                                                .addGroup(pnlCalcSoapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                                                                        .addComponent(pnlCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(33, 33, 33))))))
        );
        pnlCalcSoapLayout.setVerticalGroup(
                pnlCalcSoapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCalcSoapLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlCalcSoapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnMain)
                                        .addComponent(lblTitle))
                                .addGap(27, 27, 27)
                                .addGroup(pnlCalcSoapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblConcentration)
                                        .addComponent(cbxConcentration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMass)
                                        .addComponent(lblBulk)
                                        .addComponent(txtMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBulk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlCalcSoap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlCalcSoap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnMainActionPerformed

    private void txtMassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMassKeyTyped
        NumberField.addNumber(txtMass, evt);
    }//GEN-LAST:event_txtMassKeyTyped

    private void txtBulkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBulkKeyTyped
        NumberField.addNumber(txtBulk, evt);
    }//GEN-LAST:event_txtBulkKeyTyped


    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        if (new TxtTreatment().isTxtVoid(pnlCalcSoap)) {
            soap = new CalcSoap().getSoap(
                    Double.parseDouble(cbxConcentration.getSelectedItem().toString()),
                    Double.parseDouble(txtBulk.getText()),
                    Double.parseDouble(txtMass.getText())
            );
            if (pnlCalc.getComponents().length > 0) {
                pnlCalc.removeAll();
            }
            GridLayout layout = new GridLayout();
            pnlCalc.setLayout(layout);
            pnlCalc.add(new PnlCalcOleic(soap)).setVisible(true);

        } else {
            new EmptyField().showMsg();
        }
    }//GEN-LAST:event_btnCalculateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnMain;
    private javax.swing.JComboBox<Object> cbxConcentration;
    private javax.swing.JLabel lblBulk;
    private javax.swing.JLabel lblConcentration;
    private javax.swing.JLabel lblMass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlCalc;
    private javax.swing.JPanel pnlCalcSoap;
    private javax.swing.JTextField txtBulk;
    private javax.swing.JTextField txtMass;
    // End of variables declaration//GEN-END:variables

    private void showComboBox() {
        cbxConcentration.removeAllItems();
        new HclRequest().select().forEach(hcl -> cbxConcentration.addItem(hcl));
    }

}
