/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dev.senzalla.rectify.canvas;

import dev.senzalla.rectify.Access;

/**
 * @author Black Burn Cybernetic
 * @e-mail blackburncyber@gmail.com
 * @github github.com/BlackBurnCybernetic
 */

public class FrmLabTq extends javax.swing.JInternalFrame {

    /** Creates new form FrmLabTq */
    public FrmLabTq() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLabTk = new javax.swing.JPanel();
        btnLabTkMain = new javax.swing.JButton();
        lblLabTkTitle = new javax.swing.JLabel();
        lblLabTkName = new javax.swing.JLabel();
        cbxLabTkName = new javax.swing.JComboBox<>();
        lblLabTkAcid = new javax.swing.JLabel();
        txtLabTkAcid = new javax.swing.JTextField();
        btnLabTkAcid = new javax.swing.JButton();
        lblLabTkSoap = new javax.swing.JLabel();
        txtLabTkSoap = new javax.swing.JTextField();
        btnLabTkSoap = new javax.swing.JButton();
        lblLabTkTrash = new javax.swing.JLabel();
        txtLabTkTrash = new javax.swing.JFormattedTextField();
        btnLabTkSave = new javax.swing.JButton();
        btnLabTkClear = new javax.swing.JButton();
        btnLabTkCancel = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(598, 460));
        setMinimumSize(new java.awt.Dimension(598, 460));
        setNormalBounds(new java.awt.Rectangle(598, 460, 460, 460));
        setPreferredSize(new java.awt.Dimension(598, 460));

        pnlLabTk.setMaximumSize(new java.awt.Dimension(596, 438));
        pnlLabTk.setMinimumSize(new java.awt.Dimension(596, 438));
        pnlLabTk.setPreferredSize(new java.awt.Dimension(596, 438));

        btnLabTkMain.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLabTkMain.setText("<<");
        btnLabTkMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabTkMainActionPerformed(evt);
            }
        });

        lblLabTkTitle.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblLabTkTitle.setText("Analise Tanque");

        lblLabTkName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLabTkName.setText("Tanque");

        cbxLabTkName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblLabTkAcid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLabTkAcid.setText("Acidez");

        txtLabTkAcid.setPreferredSize(new java.awt.Dimension(120, 27));

        btnLabTkAcid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dev/senzalla/rectify/canvas/resource/calculadora_b.png"))); // NOI18N
        btnLabTkAcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabTkAcidActionPerformed(evt);
            }
        });

        lblLabTkSoap.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLabTkSoap.setText("Saponidade");

        txtLabTkSoap.setPreferredSize(new java.awt.Dimension(120, 27));

        btnLabTkSoap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dev/senzalla/rectify/canvas/resource/calculadora_b.png"))); // NOI18N
        btnLabTkSoap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabTkSoapActionPerformed(evt);
            }
        });

        lblLabTkTrash.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLabTkTrash.setText("Impureza");

        txtLabTkTrash.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtLabTkTrash.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLabTkTrash.setPreferredSize(new java.awt.Dimension(120, 27));

        btnLabTkSave.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLabTkSave.setText("Salvar");
        btnLabTkSave.setPreferredSize(new java.awt.Dimension(120, 60));
        btnLabTkSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabTkSaveActionPerformed(evt);
            }
        });

        btnLabTkClear.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLabTkClear.setText("Limpar");
        btnLabTkClear.setPreferredSize(new java.awt.Dimension(120, 60));
        btnLabTkClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabTkClearActionPerformed(evt);
            }
        });

        btnLabTkCancel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLabTkCancel.setText("Cancelar");
        btnLabTkCancel.setPreferredSize(new java.awt.Dimension(120, 60));
        btnLabTkCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabTkCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLabTkLayout = new javax.swing.GroupLayout(pnlLabTk);
        pnlLabTk.setLayout(pnlLabTkLayout);
        pnlLabTkLayout.setHorizontalGroup(
            pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabTkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabTkLayout.createSequentialGroup()
                        .addComponent(btnLabTkMain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLabTkTitle)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLabTkLayout.createSequentialGroup()
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLabTkLayout.createSequentialGroup()
                                .addComponent(lblLabTkName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxLabTkName, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLabTkLayout.createSequentialGroup()
                                .addComponent(btnLabTkSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnLabTkClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnLabTkCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(pnlLabTkLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLabTkTrash)
                    .addComponent(lblLabTkSoap)
                    .addComponent(lblLabTkAcid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlLabTkLayout.createSequentialGroup()
                        .addComponent(txtLabTkAcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLabTkAcid, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(pnlLabTkLayout.createSequentialGroup()
                        .addComponent(txtLabTkSoap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLabTkSoap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLabTkTrash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLabTkLayout.setVerticalGroup(
            pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabTkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLabTkMain)
                    .addComponent(lblLabTkTitle))
                .addGap(30, 30, 30)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLabTkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLabTkName))
                .addGap(30, 30, 30)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLabTkAcid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLabTkAcid)
                        .addComponent(txtLabTkAcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabTkSoap)
                    .addComponent(btnLabTkSoap, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLabTkSoap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabTkTrash)
                    .addComponent(txtLabTkTrash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlLabTkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLabTkSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabTkClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabTkCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLabTk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLabTk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLabTkMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabTkMainActionPerformed
        this.dispose();
        Access.goToCanvas(this, new FrmLabTqTbl());
    }//GEN-LAST:event_btnLabTkMainActionPerformed

    private void btnLabTkAcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabTkAcidActionPerformed
    }//GEN-LAST:event_btnLabTkAcidActionPerformed

    private void btnLabTkSoapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabTkSoapActionPerformed
    }//GEN-LAST:event_btnLabTkSoapActionPerformed

    private void btnLabTkSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabTkSaveActionPerformed
    }//GEN-LAST:event_btnLabTkSaveActionPerformed

    private void btnLabTkClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabTkClearActionPerformed
    }//GEN-LAST:event_btnLabTkClearActionPerformed

    private void btnLabTkCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabTkCancelActionPerformed
    }//GEN-LAST:event_btnLabTkCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLabTkAcid;
    private javax.swing.JButton btnLabTkCancel;
    private javax.swing.JButton btnLabTkClear;
    private javax.swing.JButton btnLabTkMain;
    private javax.swing.JButton btnLabTkSave;
    private javax.swing.JButton btnLabTkSoap;
    private javax.swing.JComboBox<Object> cbxLabTkName;
    private javax.swing.JLabel lblLabTkAcid;
    private javax.swing.JLabel lblLabTkName;
    private javax.swing.JLabel lblLabTkSoap;
    private javax.swing.JLabel lblLabTkTitle;
    private javax.swing.JLabel lblLabTkTrash;
    private javax.swing.JPanel pnlLabTk;
    private javax.swing.JTextField txtLabTkAcid;
    private javax.swing.JTextField txtLabTkSoap;
    private javax.swing.JFormattedTextField txtLabTkTrash;
    // End of variables declaration//GEN-END:variables

}
