/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dev.senzalla.rectify.canvas;

import dev.senzalla.rectify.Access;

/**
 * @author Black Burn Cybernetic
 * @e-mail blackburncyber@gmail.com
 * @github github.com/BlackBurnCybernetic
 */

public class FrmLabSplit extends javax.swing.JInternalFrame {

    /** Creates new form FrmLabSplit */
    public FrmLabSplit() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLabSplit = new javax.swing.JPanel();
        btnLabSplitMain = new javax.swing.JButton();
        lblLabSplitTitle = new javax.swing.JLabel();
        lblLabSplitOil = new javax.swing.JLabel();
        txtLabSplitOil = new javax.swing.JFormattedTextField();
        lblLabSplitSludge = new javax.swing.JLabel();
        txtLabSplitSludge = new javax.swing.JFormattedTextField();
        lblLabSplitGlycerin = new javax.swing.JLabel();
        txtLabSplitGlycerin = new javax.swing.JFormattedTextField();
        lblLabSplitTrash = new javax.swing.JLabel();
        txtLabSplitTrash = new javax.swing.JFormattedTextField();
        btnLabSplitSave = new javax.swing.JButton();
        btnLabSplitClear = new javax.swing.JButton();
        btnLabSplitCancel = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(598, 460));
        setMinimumSize(new java.awt.Dimension(598, 460));
        setPreferredSize(new java.awt.Dimension(598, 460));

        pnlLabSplit.setMaximumSize(new java.awt.Dimension(596, 438));
        pnlLabSplit.setMinimumSize(new java.awt.Dimension(596, 438));

        btnLabSplitMain.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLabSplitMain.setText("<<");
        btnLabSplitMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabSplitMainActionPerformed(evt);
            }
        });

        lblLabSplitTitle.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblLabSplitTitle.setText("Analise Cisão");

        lblLabSplitOil.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLabSplitOil.setText("Oleo");

        txtLabSplitOil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtLabSplitOil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLabSplitOil.setPreferredSize(new java.awt.Dimension(150, 27));

        lblLabSplitSludge.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLabSplitSludge.setText("Borra");

        txtLabSplitSludge.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtLabSplitSludge.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLabSplitSludge.setPreferredSize(new java.awt.Dimension(150, 27));

        lblLabSplitGlycerin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLabSplitGlycerin.setText("Glicerina");

        txtLabSplitGlycerin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtLabSplitGlycerin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLabSplitGlycerin.setPreferredSize(new java.awt.Dimension(150, 27));

        lblLabSplitTrash.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLabSplitTrash.setText("Impureza");

        txtLabSplitTrash.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtLabSplitTrash.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLabSplitTrash.setPreferredSize(new java.awt.Dimension(150, 27));

        btnLabSplitSave.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLabSplitSave.setText("Salvar");
        btnLabSplitSave.setPreferredSize(new java.awt.Dimension(120, 60));
        btnLabSplitSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabSplitSaveActionPerformed(evt);
            }
        });

        btnLabSplitClear.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLabSplitClear.setText("Limpar");
        btnLabSplitClear.setPreferredSize(new java.awt.Dimension(120, 60));
        btnLabSplitClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabSplitClearActionPerformed(evt);
            }
        });

        btnLabSplitCancel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLabSplitCancel.setText("Cancelar");
        btnLabSplitCancel.setPreferredSize(new java.awt.Dimension(120, 60));
        btnLabSplitCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabSplitCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLabSplitLayout = new javax.swing.GroupLayout(pnlLabSplit);
        pnlLabSplit.setLayout(pnlLabSplitLayout);
        pnlLabSplitLayout.setHorizontalGroup(
            pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabSplitLayout.createSequentialGroup()
                .addGroup(pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLabSplitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLabSplitMain)
                        .addGap(174, 174, 174)
                        .addComponent(lblLabSplitTitle))
                    .addGroup(pnlLabSplitLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLabSplitSludge)
                            .addComponent(lblLabSplitOil)
                            .addComponent(lblLabSplitGlycerin)
                            .addComponent(lblLabSplitTrash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLabSplitOil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLabSplitSludge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLabSplitGlycerin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLabSplitTrash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlLabSplitLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnLabSplitSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnLabSplitClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnLabSplitCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        pnlLabSplitLayout.setVerticalGroup(
            pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLabSplitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLabSplitMain)
                    .addComponent(lblLabSplitTitle))
                .addGap(19, 19, 19)
                .addGroup(pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabSplitOil)
                    .addComponent(txtLabSplitOil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabSplitSludge)
                    .addComponent(txtLabSplitSludge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabSplitGlycerin)
                    .addComponent(txtLabSplitGlycerin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabSplitTrash)
                    .addComponent(txtLabSplitTrash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(pnlLabSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLabSplitSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabSplitClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabSplitCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlLabSplit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLabSplit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLabSplitMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabSplitMainActionPerformed
        Access.goToCanvas(this, new FrmLabSplitTbl());
    }//GEN-LAST:event_btnLabSplitMainActionPerformed

    private void btnLabSplitSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabSplitSaveActionPerformed
    }//GEN-LAST:event_btnLabSplitSaveActionPerformed

    private void btnLabSplitClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabSplitClearActionPerformed
    }//GEN-LAST:event_btnLabSplitClearActionPerformed

    private void btnLabSplitCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabSplitCancelActionPerformed
    }//GEN-LAST:event_btnLabSplitCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLabSplitCancel;
    private javax.swing.JButton btnLabSplitClear;
    private javax.swing.JButton btnLabSplitMain;
    private javax.swing.JButton btnLabSplitSave;
    private javax.swing.JLabel lblLabSplitGlycerin;
    private javax.swing.JLabel lblLabSplitOil;
    private javax.swing.JLabel lblLabSplitSludge;
    private javax.swing.JLabel lblLabSplitTitle;
    private javax.swing.JLabel lblLabSplitTrash;
    private javax.swing.JPanel pnlLabSplit;
    private javax.swing.JFormattedTextField txtLabSplitGlycerin;
    private javax.swing.JFormattedTextField txtLabSplitOil;
    private javax.swing.JFormattedTextField txtLabSplitSludge;
    private javax.swing.JFormattedTextField txtLabSplitTrash;
    // End of variables declaration//GEN-END:variables

}
